name: Test pull request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - "master"

jobs:
  validate:
    name: Test pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Rollup
        run: pnpm run ci:packages:rollup